### ISSUE TITLE
SUGGESTION: /as tp with no arguments.

### ISSUE THREAD

**Issue by Roadhog360** [NLthijs48/AreaShop#292]
#### New behaviour

/as tp
With no arguments.

How it would work is if you have people limited to one region rental/buy like I do, you can do /as settp and /as tp with no arguments. So I don't need to do /as tp (region) (sign). Also, maybe an automatic settp based on a configurable position. (EG I buy a region, tp automatically set in the safest spot in the middle.).

ALTERNATIVE:
/as sethome and /as home.
You can set a /sethome with /as sethome inside of your rented regions. You can set 1 or more homes, like /as sethome 1, /as home 1, etc. You can also limit people's homes with permissions/config. If you did /as home or /as sethome with no arguments, it would set it as home 1 by default. This would make an argument-less version of /as tp and if someone had a large region, they could have multiple homes inside of it if they had permission.

**Comment by NLthijs48** [comment]
#39 already describes adding this feature, either by `/as home` or `/as tp` without arguments. 

`/as settp` already works without specifying a region if you are standing inside the region, so that issue is already solved. 

By default a region has the teleport location in the middle of the x and z axis, and at the lowest y location in the region. with the `teleportLocationY` setting in default.yml you can change the y location. Teleportation is always safe, so there is no need to worry about ending up inside a block or in lava (AreaShop will search around the teleport location to find a safe spot). So if a player/admin does not set a teleport location it will already work.

I also want to point out `/as me`, which shows a list of your regions, which can be clicked to get more information. After clicking one of the region there is also a button to teleport to it, so that is already quite easy.

I'll close this issue as duplicate of #39, because if that issue is solved your problem will also be fixed. Thanks for your suggestions.

**Comment by Roadhog360** [comment]
NOT solved. I do not want to go into a list to click it, I want to do /as tp without any arguments.

**Comment by NLthijs48** [comment]
That is exactly what my intention is with the other issue I linked, either letting `/as tp` going straight to your first region or adding `/as home` for that. I agree the other issue does not describe this correctly though, I updated that.

**Comment by Roadhog360** [comment]
But just to be clear... this is possible now?

**Comment by NLthijs48** [comment]
Not yet, it is only on the planned features list
