### ISSUE TITLE
Critical error in permissions

### ISSUE THREAD

**Issue by Roper89** [NLthijs48/AreaShop#427]
1) 
when using "**areashop.landlord.***" permissions, do not work: **areashop.destroyrent.landlord** and **areashop.destroybuy.landlord** (registration for rent and buy works)
Players can  delete "rent" only from the operator's rights (**areashop.destroyrent**).

2)
If i use the permission "areashop.landlord. *" Then when the command "/ as help" is used, I do not see two commands in the prompts: "**/as add**" and "**/as del**"

_(AreaShop 2.4.0, Minecraft ver. 1.12.2)_

**Comment by Roper89** [comment]
@NLthijs48  
I do not understand why permissions do not work. I can not turn off the teleporter. 
My "permissions.yml" (on disable teleport)
```
groups:
  default:
    options:
      default: true
    permissions:
    - areashop.teleportavailable
    - areashop.teleport
    - areashop.find
    - modifyworld.*
schema-version: 1
users: {}

```

My file "permissions.yml" — [drive.google.com](https://drive.google.com/open?id=1mookISqNzqcbbrE9eTy0DkU9tMelRC-1)  
Other permissions work, example: when using **areashop.landlord.***   **work:** areashop.createrent.owner, areashop.createbuy.owner, areashop.setprice.landlord, areashop.setduration.landlord and **do not work:** **areashop.destroyrent.landlord**, **areashop.destroybuy.landlord** 

I used a clean server with different builds of versions 1.12.2
I used different versions: WorldGuard, WorldEdit, Vault, economy (Essentials, Gringotts)
**PermissionsEx-1.23.4**

Help configure permissions. I can give access to the control panel of the server.

**Comment by NLthijs48** [comment]
1. What kind of message does the player get when he tries to use `/as del <region>` for the region he is landlord of? I did not find any problems in the code at first glance.
2. The help message is indeed not showing up for landlords, I'll update that!

**Comment by Roper89** [comment]
@NLthijs48  
The player receives a message that he does not have permission.

Tell you the `/as del <region>` command works for you when using it with permissions: **areashop.landlord.*** and **areashop.destroyrent.landlord** ?
I did a test on different versions and on different servers.

If everything works for you, maybe I will try to use your configurations and permissions?

**Comment by NLthijs48** [comment]
Could you install version 2.5.0 that I just released and see if that works? Otherwise I will try it out myself and see if I can reproduce your issue.

> The player receives a message that he does not have permission.
Could you show me the exact message though? That helps me a lot to find out which check in the code if failing.

**Comment by Roper89** [comment]
@NLthijs48 , On version 2.5.0, the problem remained.
When using the  `/as del` command inside the region. I get a notification:  `No permission to remove or not registered: <region>`
When using `/as del <region>` — `You don't have permission for deregistering a rental region.`

I have permission: `areashop.landlord.*`  and I can use this `/as add` command, but I can not delete after...

P.S.  Tell your email, I will send the login and password from FTP and game account with the necessary permissions.

**Comment by NLthijs48** [comment]
I found an issue in the landlord detection code that would cause that the landlord would not get set after a player adds a region to AreaShop, this should solve your issue. You can download a [development build here](http://wiefferink.me:8080/job/AreaShop/) to test it out.
